// Generated by CoffeeScript 1.9.3
var test;

test = {};

describe("Bank", function() {
  beforeEach(function() {
    return test.bank = 234;
  });
  return it("dummy test", function() {
    return expect(true).toBe(true);
  });
});
