// Generated by CoffeeScript 1.9.3
var AUTORUN_DELAY, DICT, GraphVisualizer, LANG, NUM_BANKS, Params, Simulator, TableVisualizer, Visualizer, VisualizerMgr, iv, params, simulator, translate,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty,
  slice = [].slice;

LANG = 'EN';

NUM_BANKS = 12;

translate = function(engl_word) {
  var d, e;
  if (LANG === 'EN') {
    return engl_word;
  } else if (LANG === 'DE') {
    for (e in DICT) {
      d = DICT[e];
      if (engl_word === e) {
        return d;
      }
    }
    return console.log("TODO: translate - " + e);
  }
};

DICT = {
  "table": "Tabelle",
  "diagram": "Diagramm",
  "interest": "Zins",
  "reserves": "Reserven",
  "banks": "Banken",
  "central bank": "Zentralbank",
  "capital": "Eigenkapital",
  "assets": "Aktiven",
  "liabilities": "Passiven",
  "balance sheet": "Bilanz",
  "prime rate": "Leitzins",
  "stocks": "Wertschriften",
  "statistics": "Statistiken",
  "money supply": "Geldmenge",
  "credits": "Kredite",
  "credits to banks": "Kredite an Banken",
  "debt to central bank": "Schulden an ZB",
  "bank deposits": "Giralgeld",
  "total": "Total"
};

AUTORUN_DELAY = 2000;

Simulator = (function() {
  Simulator.prototype.init = function() {
    var banks, cb, i;
    banks = (function() {
      var j, ref, results;
      results = [];
      for (i = j = 1, ref = NUM_BANKS; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        results.push(Bank.prototype.get_random_bank());
      }
      return results;
    })();
    cb = new CentralBank(banks);
    this.microeconomy = new MicroEconomy(cb, banks);
    return this.trx_mgr = new TrxMgr(this.params, this.microeconomy);
  };

  function Simulator(params1) {
    this.params = params1;
    this.init();
    this.params.set_simulator(this);
  }

  Simulator.prototype.simulate = function(years) {
    var j, ref, results;
    results = [];
    for (j = 1, ref = years; 1 <= ref ? j <= ref : j >= ref; 1 <= ref ? j++ : j--) {
      results.push(this.simulate_one_year());
    }
    return results;
  };

  Simulator.prototype.simulate_one_year = function() {
    return this.trx_mgr.one_year();
  };

  Simulator.prototype.reset = function() {
    return this.init();
  };

  return Simulator;

})();

VisualizerMgr = (function() {
  function VisualizerMgr() {}

  VisualizerMgr.prototype.vizArray = [];

  VisualizerMgr.prototype.visualize = function() {
    var j, len, ref, results, viz;
    ref = this.vizArray;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      viz = ref[j];
      results.push(viz.visualize());
    }
    return results;
  };

  VisualizerMgr.prototype.clear = function() {
    var j, len, ref, results, viz;
    ref = this.vizArray;
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      viz = ref[j];
      results.push(viz.clear());
    }
    return results;
  };

  VisualizerMgr.prototype.addViz = function(viz) {
    return this.vizArray.push(viz);
  };

  VisualizerMgr.prototype.reset = function() {
    this.clear();
    return this.vizArray = [];
  };

  return VisualizerMgr;

})();

Visualizer = (function() {
  function Visualizer(microeconomy) {
    this.microeconomy = microeconomy;
    this.banks = microeconomy.banks;
    this.cb = microeconomy.cb;
  }

  Visualizer.prototype.clear = function() {};

  Visualizer.prototype.visualize = function() {};

  return Visualizer;

})();

TableVisualizer = (function(superClass) {
  extend(TableVisualizer, superClass);

  function TableVisualizer(microeconomy1) {
    this.microeconomy = microeconomy1;
    TableVisualizer.__super__.constructor.apply(this, arguments);
  }

  TableVisualizer.prototype.clear = function() {
    TableVisualizer.__super__.clear.apply(this, arguments);
    $('#cb_table').empty();
    $('#ms_table').empty();
    return $('#banks_table').empty();
  };

  TableVisualizer.prototype.create_row = function() {
    var entries, entry, j, len, tr;
    entries = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    tr = '<tr>';
    for (j = 0, len = entries.length; j < len; j++) {
      entry = entries[j];
      tr += '<td>' + entry + '</td>';
    }
    return tr += '</tr>';
  };

  TableVisualizer.prototype.create_header = function() {
    var entries, entry, j, len, tr;
    entries = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    tr = '<tr>';
    for (j = 0, len = entries.length; j < len; j++) {
      entry = entries[j];
      tr += '<th>' + entry + '</th>';
    }
    return tr += '</tr>';
  };

  TableVisualizer.prototype.create_cb_table = function(cb) {
    var row_1, row_2, row_3, row_h;
    $('#cb_table').append('<table>');
    $('#cb_table').append('<caption>' + translate('central bank') + '</caption>');
    row_h = this.create_header(translate('assets'), '', translate('liabilities'), '');
    row_1 = this.create_row('Forderungen an Banken', cb.credits_total().toFixed(2), 'ZB Giralgeld', cb.giro_total().toFixed(2));
    row_2 = this.create_row(translate('stocks'), '0', translate('capital'), cb.capital().toFixed(2));
    row_3 = this.create_row(translate('total'), cb.assets_total().toFixed(2), '', cb.liabilities_total().toFixed(2));
    $('#cb_table').append(row_h).append(row_1).append(row_2).append(row_3);
    return $('#cb_table').append('</table>');
  };

  TableVisualizer.prototype.create_ms_table = function(cb) {
    var row, row_h;
    $('#ms_table').append('<table>');
    $('#ms_table').append('<caption>' + translate('money supply') + '</caption>');
    row_h = this.create_header('M0', 'M1', 'M2');
    row = this.create_row(cb.M0().toFixed(2), cb.M1().toFixed(2), cb.M2().toFixed(2));
    $('#ms_table').append(row_h).append(row);
    return $('#ms_table').append('</table>');
  };

  TableVisualizer.prototype.create_bank_header = function() {
    return this.create_header(translate("reserves"), translate('credits'), translate('debt to central bank'), translate('bank deposits'), translate("capital"), translate("assets"), translate("liabilities"));
  };

  TableVisualizer.prototype.create_bank_row = function(bank) {
    return this.create_row(bank.reserves.toFixed(2), bank.credits.toFixed(2), bank.debt_cb.toFixed(2), bank.giral.toFixed(2), bank.capital.toFixed(2), bank.assets_total().toFixed(2), bank.liabilities_total().toFixed(2));
  };

  TableVisualizer.prototype.create_banks_table = function(banks) {
    var bank, j, len, ref;
    $('#banks_table').append('<table>');
    $('#banks_table').append('<caption>' + translate('banks') + '</caption>');
    $('#banks_table').append(this.create_bank_header());
    ref = this.banks;
    for (j = 0, len = ref.length; j < len; j++) {
      bank = ref[j];
      $('#banks_table').append(this.create_bank_row(bank));
    }
    return $('#banks_table').append('</table>');
  };

  TableVisualizer.prototype.visualize = function() {
    this.clear();
    this.create_cb_table(this.cb);
    this.create_ms_table(this.cb);
    return this.create_banks_table(this.banks);
  };

  return TableVisualizer;

})(Visualizer);

GraphVisualizer = (function(superClass) {
  extend(GraphVisualizer, superClass);

  function GraphVisualizer(microeconomy1) {
    this.microeconomy = microeconomy1;
    GraphVisualizer.__super__.constructor.apply(this, arguments);
  }

  GraphVisualizer.prototype.clear = function() {
    $('#banks_graph').empty();
    $('#banks_total_graph').empty();
    $('#cb_graph').empty();
    return $('#stats_graph').empty();
  };

  GraphVisualizer.prototype.draw_stats = function() {
    $('#stats_graph1').highcharts({
      title: {
        text: translate("money supply")
      },
      xAxis: {
        categories: []
      },
      yAxis: {
        allowDecimals: false,
        title: {
          text: 'CHF'
        }
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '<br/>';
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal'
        },
        series: {
          animation: false
        }
      },
      series: [
        {
          name: translate('money supply M0'),
          data: this.cb.stats.m0
        }, {
          name: translate('money supply M1'),
          data: this.cb.stats.m1
        }
      ]
    });
    return $('#stats_graph2').highcharts({
      title: {
        text: translate("inflation")
      },
      xAxis: {
        categories: []
      },
      yAxis: {
        allowDecimals: false,
        title: {
          text: '%'
        }
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '<br/>';
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal'
        },
        series: {
          animation: false
        }
      },
      series: [
        {
          name: translate('inflation M0'),
          data: this.cb.stats.inflation_m0
        }, {
          name: translate('inflation M1'),
          data: this.cb.stats.inflation_m1
        }
      ]
    });
  };

  GraphVisualizer.prototype.draw_cb = function() {
    return $('#cb_graph').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: translate("central bank")
      },
      xAxis: {
        categories: []
      },
      yAxis: {
        allowDecimals: false,
        min: 0,
        title: {
          text: 'CHF'
        }
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '<br/>' + 'Total: ' + this.point.stackTotal;
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal'
        },
        series: {
          animation: false
        }
      },
      series: [
        {
          name: translate('credits to banks'),
          data: [this.cb.credits_total()],
          stack: translate('assets')
        }, {
          name: translate('stocks'),
          data: [0],
          stack: translate('assets')
        }, {
          name: 'M0',
          data: [this.cb.giro_total()],
          stack: translate('liabilities')
        }, {
          name: translate("capital"),
          data: [this.cb.capital()],
          stack: translate('liabilities')
        }
      ]
    });
  };

  GraphVisualizer.prototype.draw_banks = function() {
    var bank, caps, cbcredits, credits, girals, reserves;
    reserves = (function() {
      var j, len, ref, results;
      ref = this.banks;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        bank = ref[j];
        results.push(bank.reserves);
      }
      return results;
    }).call(this);
    credits = (function() {
      var j, len, ref, results;
      ref = this.banks;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        bank = ref[j];
        results.push(bank.credits);
      }
      return results;
    }).call(this);
    caps = (function() {
      var j, len, ref, results;
      ref = this.banks;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        bank = ref[j];
        results.push(bank.capital);
      }
      return results;
    }).call(this);
    cbcredits = (function() {
      var j, len, ref, results;
      ref = this.banks;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        bank = ref[j];
        results.push(bank.debt_cb);
      }
      return results;
    }).call(this);
    girals = (function() {
      var j, len, ref, results;
      ref = this.banks;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        bank = ref[j];
        results.push(bank.giral);
      }
      return results;
    }).call(this);
    $('#banks_graph').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: translate('banks')
      },
      xAxis: {
        categories: []
      },
      yAxis: {
        allowDecimals: false,
        min: 0,
        title: {
          text: 'CHF'
        }
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '<br/>' + 'Total: ' + this.point.stackTotal;
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal'
        },
        series: {
          animation: false
        }
      },
      series: [
        {
          name: translate("reserves"),
          data: reserves,
          stack: translate('assets')
        }, {
          name: translate('credits'),
          data: credits,
          stack: translate('assets')
        }, {
          name: translate('debt to central bank'),
          data: cbcredits,
          stack: translate('liabilities')
        }, {
          name: translate('bank deposits'),
          data: girals,
          stack: translate('liabilities')
        }, {
          name: translate("capital"),
          data: caps,
          stack: translate('liabilities')
        }
      ]
    });
    return $('#banks_total_graph').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: translate('banks consolidated')
      },
      xAxis: {
        categories: []
      },
      yAxis: {
        allowDecimals: false,
        min: 0,
        title: {
          text: 'CHF'
        }
      },
      tooltip: {
        formatter: function() {
          return '<b>' + this.x + '</b><br/>' + this.series.name + ': ' + this.y + '<br/>' + 'Total: ' + this.point.stackTotal;
        }
      },
      plotOptions: {
        column: {
          stacking: 'normal'
        },
        series: {
          animation: false
        }
      },
      series: [
        {
          name: translate("reserves"),
          data: [reserves.sum()],
          stack: translate('assets')
        }, {
          name: translate('credits'),
          data: [credits.sum()],
          stack: translate('assets')
        }, {
          name: translate('debt to central bank'),
          data: [cbcredits.sum()],
          stack: translate('liabilities')
        }, {
          name: translate('bank deposits'),
          data: [girals.sum()],
          stack: translate('liabilities')
        }, {
          name: translate("capital"),
          data: [caps.sum()],
          stack: translate('liabilities')
        }
      ]
    });
  };

  GraphVisualizer.prototype.visualize = function() {
    console.log("drawing graph... " + this.banks.length);
    this.clear();
    this.draw_cb();
    this.draw_stats();
    return this.draw_banks();
  };

  return GraphVisualizer;

})(Visualizer);

iv = function(val) {
  return ko.observable(val);
};

Params = (function() {
  function Params() {}

  Params.prototype.step = iv(0);

  Params.prototype.yearsPerStep = iv(1);

  Params.prototype.autorun = iv("off");

  Params.prototype.autorun_id = 0;

  Params.prototype.tableViz_checked = iv(true);

  Params.prototype.diagramViz_checked = iv(true);

  Params.prototype.max_trx = iv(50);

  Params.prototype.prime_rate = iv(3);

  Params.prototype.prime_rate_giro = iv(1);

  Params.prototype.cap_req = iv(8);

  Params.prototype.minimal_reserves = iv(5);

  Params.prototype.credit_interest = iv(6);

  Params.prototype.deposit_interest = iv(2);

  Params.prototype.set_simulator = function(sim) {
    this.simulator = sim;
    this.visualizerMgr = new VisualizerMgr();
    return this.set_viz();
  };

  Params.prototype.reset_params = function() {
    return this.step(0);
  };

  Params.prototype.set_viz = function() {
    this.visualizerMgr.reset();
    if (this.tableViz_checked()) {
      this.visualizerMgr.addViz(new TableVisualizer(this.simulator.microeconomy));
    }
    if (this.diagramViz_checked()) {
      return this.visualizerMgr.addViz(new GraphVisualizer(this.simulator.microeconomy));
    }
  };

  Params.prototype.viz_clicked = function() {
    this.set_viz();
    this.visualizerMgr.visualize();
    return true;
  };

  Params.prototype.lang_de_clicked = function() {
    LANG = 'DE';
    return this.visualizerMgr.visualize();
  };

  Params.prototype.lang_en_clicked = function() {
    LANG = 'EN';
    return this.visualizerMgr.visualize();
  };

  Params.prototype.simulate_clicked = function() {
    var curr_s, yps;
    yps = parseInt(this.yearsPerStep());
    curr_s = parseInt(this.step());
    this.step(yps + curr_s);
    this.simulator.simulate(yps);
    return this.visualizerMgr.visualize();
  };

  Params.prototype.autorun_clicked = function() {
    if (this.autorun() === "off") {
      this.autorun('on');
      return this.autorun_id = setInterval("params.simulate_clicked()", AUTORUN_DELAY);
    } else {
      clearInterval(this.autorun_id);
      return this.autorun("off");
    }
  };

  Params.prototype.reset_clicked = function() {
    this.reset_params();
    this.simulator.reset();
    this.set_viz();
    return this.visualizerMgr.visualize();
  };

  return Params;

})();

simulator = null;

params = null;

$(function() {
  var viewModel;
  params = new Params();
  simulator = new Simulator(params);
  params.visualizerMgr.visualize();
  viewModel = params;
  return ko.applyBindings(viewModel);
});
